name: Delete Branch After Pull Request Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Delete Branch
      if: github.event.pull_request.merged == true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
      run: |
        git fetch --prune
        git push origin --delete $BRANCH_NAME

