name: Delete Branch After Pull Request Closed

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Delete Branch
      env:
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
      run: |
        git push origin --delete $BRANCH_NAME
