name: Pull Request Comment Checker

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  comment_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has a description
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          DESCRIPTION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} | jq -r '.body')
          if [ "$DESCRIPTION" == "" ] || [ "$DESCRIPTION" == "null" ]; then
            echo "Pull request must have a description before merging."
            exit 1
          else
            echo "Pull request has a description."
          fi
